"use client";
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';
export type DiscardDetails={reason:string;quantity:string;comment:string};
export default function DiscardDialog({name,expired,onClose,onConfirm}:{name:string;expired:boolean;onClose:()=>void;onConfirm:(v:DiscardDetails)=>Promise<void>}){
 const [v,set]=useState<DiscardDetails>({reason:expired?'dlc_expired':'surplus',quantity:'',comment:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="discard-dialog"><DialogHeader><DialogTitle>Déclarer le produit jeté</DialogTitle><DialogDescription>{name} · Le lot restant sera clôturé, sans supprimer sa fiche.</DialogDescription></DialogHeader><label className="field">Motif<select className="input" value={v.reason} onChange={e=>set({...v,reason:e.target.value})}><option value="dlc_expired" disabled={!expired}>DLC dépassée</option><option value="quality">Qualité / anomalie</option><option value="surplus">Surplus non utilisé</option><option value="other">Autre</option></select></label><label className="field">Quantité réellement jetée (facultatif)<Input className="input" maxLength={80} placeholder="Ex. 1,5 kg ou 3 portions" value={v.quantity} onChange={e=>set({...v,quantity:e.target.value})}/></label><label className="field">Commentaire<Textarea className="input" maxLength={500} value={v.comment} onChange={e=>set({...v,comment:e.target.value})}/></label>{error&&<p role="alert">{error}</p>}<DialogFooter><Button className="button" variant="outline" disabled={busy} onClick={onClose}>Annuler</Button><Button className="button danger" disabled={busy} onClick={async()=>{setBusy(true);try{await onConfirm(v);onClose();}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible.');}finally{setBusy(false);}}}>{busy?'Enregistrement…':'Confirmer le rejet'}</Button></DialogFooter></DialogContent></Dialog>;
}
