"use client";

import { useEffect, useState } from "react";
import { Check, LoaderCircle, RefreshCw, ShieldCheck, ShieldMinus, ShieldPlus, UserRoundCheck, UserRoundX } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { TeamMember } from "@/lib/access-types";

async function teamApi<T>(url:string,options?:RequestInit):Promise<T> {const response=await fetch(url,{...options,cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error??"La demande a échoué.");return data;}
function dateTime(value:string) {return new Intl.DateTimeFormat("fr-FR",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Paris"}).format(new Date(value));}

export default function TeamPanel() {
  const [members,setMembers]=useState<TeamMember[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [updating,setUpdating]=useState<string|null>(null);
  async function load() {setLoading(true);setError("");try{const data=await teamApi<{members:TeamMember[]}>("/api/team?offset=0");setMembers(data.members);}catch(caught){setError(caught instanceof Error?caught.message:"Impossible de charger l’équipe.");}finally{setLoading(false);}}
  useEffect(()=>{let active=true;const refresh=()=>teamApi<{members:TeamMember[]}>("/api/team?offset=0").then(data=>{if(active){setMembers(data.members);setError("");}}).catch(caught=>{if(active)setError(caught instanceof Error?caught.message:"Impossible de charger l’équipe.");}).finally(()=>{if(active)setLoading(false);});void refresh();const timer=window.setInterval(refresh,30000);window.addEventListener("focus",refresh);return()=>{active=false;window.clearInterval(timer);window.removeEventListener("focus",refresh);};},[]);
  async function change(member:TeamMember,change:{status?:"active"|"revoked";role?:"admin"|"contributor"}) {setUpdating(member.id);setError("");try{const data=await teamApi<{member:TeamMember}>("/api/team",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:member.id,revision:member.revision,...change})});setMembers(current=>current.map(item=>item.id===member.id?data.member:item));}catch(caught){setError(caught instanceof Error?caught.message:"Impossible de modifier cet accès.");}finally{setUpdating(null);}}
  const pending=members.filter(member=>member.status==="pending");const others=members.filter(member=>member.status!=="pending");
  return <div className="team-layout">
    <div className="panel panel-pad team-intro"><div className="team-title-row"><div className="team-symbol"><ShieldCheck size={28}/></div><div><h2>Accès à l’équipe</h2><p>Acceptez les utilisateurs puis choisissez leur niveau d’accès.</p></div></div><div className="notice"><Check size={18}/><span>Un administrateur peut gérer les opérations HACCP, les étiquettes, les lots et les rapports. Seul le propriétaire peut nommer des administrateurs, gérer les accès, Excel et les réglages globaux.</span></div><p className="muted-note">Les nouvelles demandes sont vérifiées automatiquement toutes les 30 secondes lorsque le site est ouvert.</p><Button variant="outline" className="button" onClick={load} disabled={loading}><RefreshCw size={16} className={loading?"spinner":""}/>Actualiser les demandes</Button></div>
    {error&&<div className="notice error" role="alert">{error}</div>}
    <section className="panel team-section" aria-labelledby="pending-title"><div className="team-section-head"><div><h2 id="pending-title">Demandes en attente</h2><p>{pending.length} demande{pending.length!==1?"s":""} à traiter</p></div></div>{loading?<div className="loading"><LoaderCircle className="spinner" size={22}/>Chargement…</div>:pending.length===0?<div className="team-empty">Aucune demande en attente.</div>:<div className="member-list">{pending.map(member=><MemberRow key={member.id} member={member} busy={updating===member.id} onChange={change}/>)}</div>}</section>
    <section className="panel team-section" aria-labelledby="members-title"><div className="team-section-head"><div><h2 id="members-title">Membres et accès retirés</h2><p>Réactivez ou retirez un accès à tout moment.</p></div></div>{!loading&&others.length===0?<div className="team-empty">Aucun autre membre pour le moment.</div>:<div className="member-list">{others.map(member=><MemberRow key={member.id} member={member} busy={updating===member.id} onChange={change}/>)}</div>}</section>
  </div>;
}

function MemberRow({member,busy,onChange}:{member:TeamMember;busy:boolean;onChange:(member:TeamMember,change:{status?:"active"|"revoked";role?:"admin"|"contributor"})=>void}) {return <div className="member-row"><div className="member-main"><div className="member-avatar" aria-hidden="true">{(member.displayName||member.email).slice(0,1).toUpperCase()}</div><div><strong>{member.displayName||member.email}</strong><span>{member.email}</span><small>Demande du {dateTime(member.requestedAt)}</small></div></div><div className="member-actions"><span className={`status-pill ${member.status==="active"?"ok":member.status==="pending"?"warn":""}`}>{member.status==="active"?"Autorisé":member.status==="pending"?"En attente":"Retiré"}</span>{member.status==="active"&&<span className={`status-pill ${member.role==="admin"?"admin-role":""}`}>{member.role==="admin"?"Administrateur":"Collaborateur"}</span>}{member.status!=="active"?<Button className="button primary" onClick={()=>onChange(member,{status:"active"})} disabled={busy}>{busy?<LoaderCircle className="spinner" size={16}/>:<UserRoundCheck size={16}/>}Accepter</Button>:<>{member.role==="admin"?<Button variant="outline" className="button" onClick={()=>onChange(member,{role:"contributor"})} disabled={busy}>{busy?<LoaderCircle className="spinner" size={16}/>:<ShieldMinus size={16}/>}Passer collaborateur</Button>:<Button variant="outline" className="button admin-button" onClick={()=>onChange(member,{role:"admin"})} disabled={busy}>{busy?<LoaderCircle className="spinner" size={16}/>:<ShieldPlus size={16}/>}Nommer administrateur</Button>}<Button variant="outline" className="button danger-button" onClick={()=>onChange(member,{status:"revoked"})} disabled={busy}>{busy?<LoaderCircle className="spinner" size={16}/>:<UserRoundX size={16}/>}Retirer</Button></>}</div></div>;}
