import {db} from './server';
import {findPrevious} from './preparation-history-server';
import {freezeSourceProblem,type PreviousPreparation} from './preparation-history';
import {validUuid} from './supply';
import type {NormalizedLabelPayload} from './label-payload';
export class LineageError extends Error { constructor(message:string,public status=400){super(message);} }
export async function prepareLineage(payload:Record<string,unknown>,v:NormalizedLabelPayload,id:string,now:string,access:{ownerId:string;userId:string;displayName:string}){
 const {ownerId,userId,displayName}=access,sourceId=String(payload.previousPreparationId??v.sourceLabelId??''),kind=String(payload.previousPreparationKind??'classic'),transform=payload.transformSource===true,scope=payload.transformationScope==='all'?'all':'partial',reason=String(payload.transformationReason??'').trim().slice(0,500),database=db();
 let source:PreviousPreparation|null=null;
 if(sourceId){if(!validUuid(sourceId)||(kind!=='classic'&&kind!=='quick'))throw new LineageError('Fiche source invalide.');source=await findPrevious(ownerId,kind,sourceId);if(!source)throw new LineageError('La fiche source n’existe pas dans ce registre.',404);v.sourceLabelId=source.kind==='classic'?source.id:null;v.sourceLotIds=[...new Set([...v.sourceLotIds,...source.sourceLotIds])];}
 if(transform){if(!source||v.preset.processType!=='frozen_in_house'||!v.frozenAt)throw new LineageError('Sélectionnez la préparation d’origine et l’opération de congélation.');const problem=freezeSourceProblem(source,v.frozenAt);if(problem)throw new LineageError(problem,409);if(payload.freezingConfirmed!==true||!reason||!v.quantity)throw new LineageError('Confirmez la procédure, la quantité congelée et le motif de la transformation.');}
 const table=source?.kind==='quick'?'internal_preparations':'preparation_labels',status=source?.kind==='quick'?"status='prepared' AND deleted_at IS NULL":"lifecycle_status='active' AND deleted_at IS NULL",guard=transform&&source?` AND EXISTS(SELECT 1 FROM ${table} WHERE owner_id=? AND id=? AND revision=? AND ${status})`:'',guardValues=transform&&source?[ownerId,source.id,source.revision]:[],created='EXISTS(SELECT 1 FROM preparation_labels WHERE owner_id=? AND id=?)';
 const statements=source?[database.prepare(`INSERT INTO preparation_lineage(id,owner_id,source_kind,source_id,target_label_id,relation,source_snapshot,reason,scope,created_at,created_by_id,created_by_name) SELECT ?,?,?,?,?,?,?,?,?,?,?,? WHERE ${created}`).bind(crypto.randomUUID(),ownerId,source.kind,source.id,id,transform?'frozen':'linked',JSON.stringify(source),reason,scope,now,userId,displayName,ownerId,id)]:[];
 if(transform&&source){if(scope==='all'){
  statements.push(source.kind==='classic'?database.prepare(`UPDATE preparation_labels SET lifecycle_status='transformed_frozen',lifecycle_updated_at=?,lifecycle_updated_by_id=?,lifecycle_updated_by_name=?,revision=revision+1,updated_at=?,updated_by_id=?,updated_by_name=? WHERE owner_id=? AND id=? AND revision=? AND ${created}`).bind(now,userId,displayName,now,userId,displayName,ownerId,source.id,source.revision,ownerId,id):database.prepare(`UPDATE internal_preparations SET status='transformed_frozen',revision=revision+1,updated_at=?,updated_by_id=?,updated_by_name=? WHERE owner_id=? AND id=? AND revision=? AND deleted_at IS NULL AND ${created}`).bind(now,userId,displayName,ownerId,source.id,source.revision,ownerId,id));
  if(source.kind==='quick'){statements.push(database.prepare(`UPDATE preparation_bacs SET status='transformed_frozen',updated_at=? WHERE owner_id=? AND preparation_id=? AND ${created}`).bind(now,ownerId,source.id,ownerId,id));statements.push(database.prepare(`UPDATE physical_labels SET status='transformed_frozen',updated_at=? WHERE owner_id=? AND preparation_id=? AND status!='printing' AND ${created}`).bind(now,ownerId,source.id,ownerId,id));}
 }
 statements.push(database.prepare(`INSERT INTO traceability_audit_events(id,owner_id,entity_type,entity_id,action,field_name,old_value,new_value,reason,changed_at,changed_by_id,changed_by_name) SELECT ?,?,?,?,?,?,?,?,?,?,?,? WHERE ${created}`).bind(crypto.randomUUID(),ownerId,source.kind==='classic'?'preparation_label':'preparation',source.id,'transformation','linked_frozen_label',source.reference,id,`${scope==='all'?'Total restant':'Partie du lot'} · ${v.quantity} · ${reason}`,now,userId,displayName,ownerId,id));
 }return{guard,guardValues,statements};
}
