import {db,json} from './server';
import {validUuid} from './supply';
import {parisNow} from './preparation-history';
export async function recordLifecycle(access:{ownerId:string;userId:string;displayName:string},payload:Record<string,unknown>){
 const id=String(payload.id??''),kind=String(payload.kind??''),action=String(payload.action??'');if(!validUuid(id)||!['classic','quick'].includes(kind)||!['consumed','discarded','transformed_frozen'].includes(action))return json({error:'Action ou étiquette invalide.'},400);
 const discard=payload.discard as Record<string,unknown>|undefined,reason=String(discard?.reason??'unspecified'),quantity=String(discard?.quantity??'').trim(),comment=String(discard?.comment??'').trim();if(action==='discarded'&&(!['dlc_expired','quality','surplus','other','unspecified'].includes(reason)||quantity.length>80||comment.length>500))return json({error:'Vérifiez le motif et la quantité jetée.'},400);
 const table=kind==='classic'?'preparation_labels':'internal_preparations',field=kind==='classic'?'lifecycle_status':'status',{ownerId,userId,displayName}=access,database=db(),now=new Date().toISOString();
 const current=await database.prepare(`SELECT ${field} AS status,expires_at,revision FROM ${table} WHERE owner_id=? AND id=? AND deleted_at IS NULL`).bind(ownerId,id).first<{status:string;expires_at:string;revision:number}>();if(!current)return json({error:'Fiche introuvable.'},404);if(current.status===action)return json({id,kind,status:action});const frozenClosure=current.status==='transformed_frozen'&&['consumed','discarded'].includes(action);if(!['active','prepared','expired'].includes(current.status)&&!frozenClosure)return json({error:'Cette préparation a déjà été clôturée.'},409);
 if(action==='transformed_frozen'&&current.expires_at<=parisNow())return json({error:'Un produit dont la DLC est dépassée ne peut pas être déclaré congelé.'},409);
 if(action==='discarded'&&reason==='dlc_expired'&&current.expires_at>parisNow())return json({error:'La DLC n’est pas encore dépassée. Choisissez le motif réel du rejet.'},400);
 const eventId=crypto.randomUUID(),entity=kind==='classic'?'preparation_label':'preparation',changed='EXISTS(SELECT 1 FROM traceability_audit_events WHERE owner_id=? AND id=?)',guard=[ownerId,eventId];
 const statements=[kind==='classic'?database.prepare('UPDATE preparation_labels SET lifecycle_status=?,lifecycle_updated_at=?,lifecycle_updated_by_id=?,lifecycle_updated_by_name=?,revision=revision+1,updated_at=?,updated_by_id=?,updated_by_name=? WHERE owner_id=? AND id=? AND revision=? AND lifecycle_status=? AND deleted_at IS NULL').bind(action,now,userId,displayName,now,userId,displayName,ownerId,id,current.revision,current.status):database.prepare('UPDATE internal_preparations SET status=?,revision=revision+1,updated_at=?,updated_by_id=?,updated_by_name=? WHERE owner_id=? AND id=? AND revision=? AND status=? AND deleted_at IS NULL').bind(action,now,userId,displayName,ownerId,id,current.revision,current.status)];
 // changes() gates a unique event inside the same atomic D1 batch, including concurrent requests.
 statements.push(database.prepare('INSERT INTO traceability_audit_events(id,owner_id,entity_type,entity_id,action,field_name,old_value,new_value,reason,changed_at,changed_by_id,changed_by_name) SELECT ?,?,?,?,?,?,?,?,?,?,?,? WHERE changes()=1').bind(eventId,ownerId,entity,id,'status',field,current.status,action,String(payload.reason??'Action déclarée par l’utilisateur sur la fiche HACCP.').slice(0,500),now,userId,displayName));
 if(kind==='quick'){statements.push(database.prepare(`UPDATE preparation_bacs SET status=?,updated_at=? WHERE owner_id=? AND preparation_id=? AND ${changed}`).bind(action,now,ownerId,id,...guard));statements.push(database.prepare(`UPDATE physical_labels SET status=?,updated_at=? WHERE owner_id=? AND preparation_id=? AND status!='printing' AND ${changed}`).bind(action,now,ownerId,id,...guard));}
 if(action==='discarded')statements.push(database.prepare(`INSERT INTO traceability_audit_events(id,owner_id,entity_type,entity_id,action,field_name,old_value,new_value,reason,changed_at,changed_by_id,changed_by_name) SELECT ?,?,?,?,?,?,?,?,?,?,?,? WHERE ${changed}`).bind(crypto.randomUUID(),ownerId,entity,id,'status','discard_details',null,JSON.stringify({reason,quantity,comment,expiredAtDiscard:current.expires_at<=parisNow()}),comment||'Détail du rejet',now,userId,displayName,...guard));
 const [updated]=await database.batch(statements);if(!updated.meta.changes)return json({error:'La fiche vient de changer. Actualisez avant de réessayer.'},409);return json({id,kind,status:action});
}
