import {authorize} from '@/lib/access';
import {db,json} from '@/lib/server';
import {isLocalDate} from '@/lib/labels';
import {parisNow} from '@/lib/preparation-history';
export const dynamic='force-dynamic';
export async function GET(request:Request){const auth=await authorize();if('response'in auth)return auth.response;const p=new URL(request.url).searchParams,from=p.get('from')??'',to=p.get('to')??'';if(from&&!isLocalDate(from)||to&&!isLocalDate(to)||from&&to&&from>to)return json({error:'Période invalide.'},400);
 try{const rows=await db().prepare(`SELECT p.*,(SELECT a.new_value FROM traceability_audit_events a WHERE a.owner_id=p.owner_id AND a.entity_id=p.id AND a.field_name='discard_details' ORDER BY a.changed_at DESC LIMIT 1) AS discard_details,(SELECT a.reason FROM traceability_audit_events a WHERE a.owner_id=p.owner_id AND a.entity_id=p.id AND a.new_value='discarded' ORDER BY a.changed_at DESC LIMIT 1) AS legacy_reason FROM (
 SELECT id,owner_id,'classic' AS kind,product_name AS name,lot_code AS reference,expires_at,quantity,lifecycle_updated_at AS discarded_at,lifecycle_updated_by_name AS discarded_by,CASE WHEN deleted_at IS NULL THEN '/preparations/'||id ELSE NULL END AS href FROM preparation_labels WHERE owner_id=? AND lifecycle_status='discarded'
 UNION ALL SELECT p.id,p.owner_id,'quick',p.ingredient_name,p.preparation_code,p.expires_at,CAST(p.bac_count AS TEXT)||' bac(s)',COALESCE((SELECT a.changed_at FROM traceability_audit_events a WHERE a.owner_id=p.owner_id AND a.entity_id=p.id AND a.new_value='discarded' ORDER BY a.changed_at DESC LIMIT 1),p.updated_at),COALESCE((SELECT a.changed_by_name FROM traceability_audit_events a WHERE a.owner_id=p.owner_id AND a.entity_id=p.id AND a.new_value='discarded' ORDER BY a.changed_at DESC LIMIT 1),p.updated_by_name),'/t/'||(SELECT MIN(l.short_token) FROM physical_labels l WHERE l.owner_id=p.owner_id AND l.preparation_id=p.id) FROM internal_preparations p WHERE p.owner_id=? AND p.deleted_at IS NULL AND p.status='discarded')p ORDER BY discarded_at DESC LIMIT 2001`).bind(auth.access.ownerId,auth.access.ownerId).all<Record<string,unknown>>();
 const items=rows.results.slice(0,2000).map(r=>{let d:Record<string,unknown>={};try{d=JSON.parse(String(r.discard_details??'{}'));}catch{}const local=r.discarded_at?parisNow(new Date(String(r.discarded_at))):'';return{id:String(r.id),kind:String(r.kind),name:String(r.name),reference:String(r.reference),expiresAt:String(r.expires_at),discardedAt:local,discardedBy:String(r.discarded_by??'Non renseigné'),quantity:String(d.quantity||'Non renseignée'),reason:String(d.reason??'unspecified'),comment:String(d.comment??r.legacy_reason??''),expiredAtDiscard:local?String(r.expires_at)<=local:null,href:r.href?String(r.href):null};}).filter(i=>(!from||i.discardedAt.slice(0,10)>=from)&&(!to||i.discardedAt.slice(0,10)<=to));return json({items,truncated:rows.results.length>2000});
 }catch(e){console.error('waste register failed',e);return json({error:'Le registre des rejets est indisponible.'},503);}}
